version: 2

sources:
  - name: raw_meter_readings
    description: "Raw meter readings loaded from GCS"
    database: "{{ env_var('GCP_PROJECT_ID', 'testing-444715') }}"
    schema: raw_meter_readings # The BigQuery Dataset ID
    tables:
      - name: smart_meters_clean
        description: "Cleaned smart meter data with quarter information"
        columns:
          - name: METER_ID
            tests:
              - not_null
          - name: DATA_TIME
            tests:
              - not_null
          - name: ROW_HASH
            tests:
              - unique
              - not_null
