version: 2

sources:
  - name: raw_meter_readings
    description: "Raw meter readings loaded from GCS"
    database: "{{ env_var('GCP_PROJECT_ID', 'testing-444715') }}"
    schema: raw_meter_readings # The BigQuery Dataset ID
    tables:
      - name: smart_meters_clean
        description: "Cleaned smart meter readings with deduplication and type casting."
        tests:
          - unique:
              column_name: ROW_HASH
          - not_null:
              column_name: ROW_HASH
          - not_null:
              column_name: METER_ID
          - not_null:
              column_name: DATA_TIME


